# Generated by Django 5.2.4 on 2025-07-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_student_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_verified',
        ),
    ]
