# Generated by Django 5.2.4 on 2025-09-15 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesettings',
            name='absent_threshold',
            field=models.TimeField(default=datetime.time(21, 30)),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='late_threshold',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='on_time_threshold',
            field=models.TimeField(default=datetime.time(20, 10)),
        ),
    ]
