# Generated by Django 5.2.4 on 2025-09-15 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancesettings_absent_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesettings',
            name='absent_threshold',
            field=models.TimeField(default=datetime.time(10, 30)),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='late_threshold',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='on_time_threshold',
            field=models.TimeField(default=datetime.time(9, 10)),
        ),
    ]
