# Generated by Django 5.2.4 on 2025-09-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendancesettings_absent_threshold_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmotionLog',
        ),
    ]
